export function mapListItemToMetrics(item: PlaceListItem) {
  return {
    visitorReviewsTotal: item.visitorReviewCount,
    visitorReviewsScore: item.visitorReviewScore || 0,
    cafeBlogReviewsTotal: item.blogCafeReviewCount,
    saveCount: item.saveCountMin || 0,
    bookmarkCount: 0,
    textReviewsTotal: 0,
    hasTalktalk: item.hasTalktalk,
    hasSmartCall: false,
    photoCount: item.imageCount,
    menuCount: 0,
    totalVoteCount: 0,
    descriptionLength: 0,
    hasReviewPenalty: false,
    isNewOpening: false,
    hasNaverBooking: item.hasBooking,
    hasSmartOrder: false,
    couponCount: 0,
    reviewMediasTotal: 0,
    isGoodStore: false,
    isOpenNow: false,
    isBizHourMissing: false,
    isMenuImageMissing: false,
    isAccessorMissing: false,
    isDescriptionMissing: false,
    isConveniencesMissing: false,
  };
}
